//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("TygaSoft.Services.HnztcSysService", ClrNamespace="TygaSoft.Services.HnztcSysService")]

namespace TygaSoft.Services.HnztcSysService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyslogInfo", Namespace="TygaSoft.Services.HnztcSysService")]
    public partial class SyslogInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppNameField;
        
        private object IdField;
        
        private System.DateTime LastUpdatedDateField;
        
        private string MessageField;
        
        private string MethodNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName
        {
            get
            {
                return this.AppNameField;
            }
            set
            {
                this.AppNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate
        {
            get
            {
                return this.LastUpdatedDateField;
            }
            set
            {
                this.LastUpdatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName
        {
            get
            {
                return this.MethodNameField;
            }
            set
            {
                this.MethodNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="TygaSoft.Services.HnztcSysService", ConfigurationName="IHnztcSys")]
public interface IHnztcSys
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="TygaSoft.Services.HnztcSysService/IHnztcSys/InsertSysLog")]
    void InsertSysLog(TygaSoft.Services.HnztcSysService.SyslogInfo syslogInfo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IHnztcSysChannel : IHnztcSys, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class HnztcSysClient : System.ServiceModel.ClientBase<IHnztcSys>, IHnztcSys
{
    
    public HnztcSysClient()
    {
    }
    
    public HnztcSysClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HnztcSysClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HnztcSysClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HnztcSysClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void InsertSysLog(TygaSoft.Services.HnztcSysService.SyslogInfo syslogInfo)
    {
        base.Channel.InsertSysLog(syslogInfo);
    }
}
