//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="TygaSoft.Services.WebSecurityService", ConfigurationName="IWebSecurity")]
public interface IWebSecurity
{
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.WebSecurityService/IWebSecurity/Login", ReplyAction="TygaSoft.Services.WebSecurityService/IWebSecurity/LoginResponse")]
    string Login(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.WebSecurityService/IWebSecurity/GetUserId", ReplyAction="TygaSoft.Services.WebSecurityService/IWebSecurity/GetUserIdResponse")]
    object GetUserId(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.WebSecurityService/IWebSecurity/ValidateUser", ReplyAction="TygaSoft.Services.WebSecurityService/IWebSecurity/ValidateUserResponse")]
    bool ValidateUser(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.WebSecurityService/IWebSecurity/GetUserByUsername", ReplyAction="TygaSoft.Services.WebSecurityService/IWebSecurity/GetUserByUsernameResponse")]
    string GetUserByUsername(string username);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWebSecurityChannel : IWebSecurity, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WebSecurityClient : System.ServiceModel.ClientBase<IWebSecurity>, IWebSecurity
{
    
    public WebSecurityClient()
    {
    }
    
    public WebSecurityClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WebSecurityClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebSecurityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebSecurityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Login(string username, string password)
    {
        return base.Channel.Login(username, password);
    }
    
    public object GetUserId(string username)
    {
        return base.Channel.GetUserId(username);
    }
    
    public bool ValidateUser(string username, string password)
    {
        return base.Channel.ValidateUser(username, password);
    }
    
    public string GetUserByUsername(string username)
    {
        return base.Channel.GetUserByUsername(username);
    }
}
