//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="TygaSoft.Services.CollectLifeService", ConfigurationName="ICollectLife")]
public interface ICollectLife
{
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/GetAnnouncementList", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/GetAnnouncementListResponse")]
    string GetAnnouncementList(int pageIndex, int pageSize);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/GetAnnouncementModel", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/GetAnnouncementModelResponse")]
    string GetAnnouncementModel(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/SavePublicComplainRepair", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/SavePublicComplainRepairRespons" +
        "e")]
    string SavePublicComplainRepair(string username, string phone, string descri);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/SaveHouseOwnerComplainRepair", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/SaveHouseOwnerComplainRepairRes" +
        "ponse")]
    string SaveHouseOwnerComplainRepair(string username, string address, string phone, string descri);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/GetComplainRepairList", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/GetComplainRepairListResponse")]
    string GetComplainRepairList(int pageIndex, int pageSize, int repairType, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/GetComplainRepairModel", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/GetComplainRepairModelResponse")]
    string GetComplainRepairModel(System.Guid Id, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/GetNoticeList", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/GetNoticeListResponse")]
    string GetNoticeList(int pageIndex, int pageSize, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/GetNoticeModel", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/GetNoticeModelResponse")]
    string GetNoticeModel(System.Guid Id, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/GetSiteFunList", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/GetSiteFunListResponse")]
    string GetSiteFunList();
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/GetAdvertisementList", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/GetAdvertisementListResponse")]
    string GetAdvertisementList(int pageIndex, int pageSize, System.Guid siteFunId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.CollectLifeService/ICollectLife/GetAdvertisementModel", ReplyAction="TygaSoft.Services.CollectLifeService/ICollectLife/GetAdvertisementModelResponse")]
    string GetAdvertisementModel(System.Guid Id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICollectLifeChannel : ICollectLife, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CollectLifeClient : System.ServiceModel.ClientBase<ICollectLife>, ICollectLife
{
    
    public CollectLifeClient()
    {
    }
    
    public CollectLifeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CollectLifeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CollectLifeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CollectLifeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetAnnouncementList(int pageIndex, int pageSize)
    {
        return base.Channel.GetAnnouncementList(pageIndex, pageSize);
    }
    
    public string GetAnnouncementModel(System.Guid Id)
    {
        return base.Channel.GetAnnouncementModel(Id);
    }
    
    public string SavePublicComplainRepair(string username, string phone, string descri)
    {
        return base.Channel.SavePublicComplainRepair(username, phone, descri);
    }
    
    public string SaveHouseOwnerComplainRepair(string username, string address, string phone, string descri)
    {
        return base.Channel.SaveHouseOwnerComplainRepair(username, address, phone, descri);
    }
    
    public string GetComplainRepairList(int pageIndex, int pageSize, int repairType, string username)
    {
        return base.Channel.GetComplainRepairList(pageIndex, pageSize, repairType, username);
    }
    
    public string GetComplainRepairModel(System.Guid Id, string username)
    {
        return base.Channel.GetComplainRepairModel(Id, username);
    }
    
    public string GetNoticeList(int pageIndex, int pageSize, string username)
    {
        return base.Channel.GetNoticeList(pageIndex, pageSize, username);
    }
    
    public string GetNoticeModel(System.Guid Id, string username)
    {
        return base.Channel.GetNoticeModel(Id, username);
    }
    
    public string GetSiteFunList()
    {
        return base.Channel.GetSiteFunList();
    }
    
    public string GetAdvertisementList(int pageIndex, int pageSize, System.Guid siteFunId)
    {
        return base.Channel.GetAdvertisementList(pageIndex, pageSize, siteFunId);
    }
    
    public string GetAdvertisementModel(System.Guid Id)
    {
        return base.Channel.GetAdvertisementModel(Id);
    }
}
